
# run: conda env create --file environment.yml

name: heroku
channels: default
dependencies:
 - python=3.7
 - pip
 - pip: 
 - pandas 
 - numpy
 - hvplot
 - matplotlib
 - panel
 - ipywidgets


